version: '3.1'
services:
  db-read:
    image: postgres
    container_name: postgres1
    volumes:
      - ./postgres-data1:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: read
      POSTGRES_USER: postgres
      POSTGRES_DB: read
  db-write:
    image: postgres
    container_name: postgres2
    volumes:
      - ./postgres-data2:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: write
      POSTGRES_USER: postgres
      POSTGRES_DB: write